#!/bin/bash
#PBS -N [name of job]
#PBS -l ncpus=[ncpus]
#PBS -l mem=[XXGB]
#PBS -l walltime=[XXh:XXm:XXs]
#PBS -j oe
#PBS -P q97
#PBS -q normal
#PBS -r n
#PBS -l wd
#PBS -M [email address]

# Load Modules
module unload openmpi
module load openmpi/1.10.3

#Change into the directory where we executed this script (otherwise it will try and run in /home/unikey)
cd $PBS_O_WORKDIR

mpirun -np [ncpus] [path/to/executable]
exit
